In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
excel_file= pd.read_excel(r"C:\Users\TITAS\Downloads\P12-Churn-Modelling.xlsx")

In [6]:
excel_file.to_csv(r"C:\Users\TITAS\Downloads\P12-Churn-Modelling.csv",index = None, header=True)

In [7]:
data= pd.read_csv(r"C:\Users\TITAS\Downloads\P12-Churn-Modelling.csv")

In [29]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [14]:
data.shape

(10000, 14)

In [19]:
data_edited=data.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1)

In [33]:
data_edited.head(50)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0           619       0   42       2       0.00              1          1   
1           608       0   41       1   83807.86              1          0   
2           502       0   42       8  159660.80              3          1   
3           699       0   39       1       0.00              2          0   
4           850       0   43       2  125510.82              1          1   
5           645       1   44       8  113755.78              2          1   
6           822       1   50       7       0.00              2          1   
7           376       0   29       4  115046.74              4          1   
8           501       1   44       4  142051.07              2          0   
9           684       1   27       2  134603.88              1          1   
10          528       1   31       6  102016.72              2          0   
11          497       1   24       3       0.00              2          1   
12          476       0   34      10       0.00              2          1   
13          549       0   25       5       0.00              2          0   
14          635       0   35       7       0.00              2          1   
15          616       1   45       3  143129.41              2          0   
16          653       1   58       1  132602.88              1          1   
17          549       0   24       9       0.00              2          1   
18          587       1   45       6       0.00              1          0   
19          726       0   24       6       0.00              2          1   
20          732       1   41       8       0.00              2          1   
21          636       0   32       8       0.00              2          1   
22          510       0   38       4       0.00              1          1   
23          669       1   46       3       0.00              2          0   
24          846       0   38       5       0.00              1          1   
25          577       1   25       3       0.00              2          0   
26          756       1   36       2  136815.64              1          1   
27          571       1   44       9       0.00              2          0   
28          574       0   43       3  141349.43              1          1   
29          411       1   29       0   59697.17              2          1   
30          591       0   39       3       0.00              3          1   
31          533       1   36       7   85311.70              1          0   
32          553       1   41       9  110112.54              2          0   
33          520       0   42       6       0.00              2          1   
34          722       0   29       9       0.00              2          1   
35          475       0   45       0  134264.04              1          1   
36          490       1   31       3  145260.23              1          0   
37          804       1   33       7   76548.60              1          0   
38          850       1   36       7       0.00              1          1   
39          582       1   41       6   70349.48              2          0   
40          472       1   40       4       0.00              1          1   
41          465       0   51       8  122522.32              1          0   
42          556       0   61       2  117419.35              1          1   
43          834       0   49       2  131394.56              1          0   
44          660       0   61       5  155931.11              1          1   
45          776       0   32       4  109421.13              2          1   
46          829       0   27       9  112045.67              1          1   
47          637       0   39       9  137843.80              1          1   
48          550       1   38       2  103391.38              1          0   
49          776       0   37       2  103769.22              2          1   

    IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0           

In [21]:
data_target=data['Exited']

In [22]:
data_target.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
label1=LabelEncoder()
data_edited['Geography']=label1.fit_transform(data_edited['Geography'])

In [27]:
label2=LabelEncoder()
data_edited['Gender']=label2.fit_transform(data_edited['Gender'])

In [31]:
data_edited=pd.get_dummies(data_edited,drop_first=True,columns=['Geography'])

In [77]:
x_train,x_test,y_train,y_test=train_test_split(data_edited,data_target,test_size=0.1,random_state=0,stratify=data_target)

In [78]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [92]:
y_train=y_train.to_numpy()
y_train

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [93]:
x_train

array([[ 0.09550008, -1.09223736, -1.5185832 , ..., -0.1682783 ,
         1.72897707, -0.57444212],
       [-0.24579325, -1.09223736, -0.18355569, ...,  0.56945842,
         1.72897707, -0.57444212],
       [-0.4112688 , -1.09223736,  1.34219004, ...,  0.97639205,
        -0.57837667, -0.57444212],
       ...,
       [ 2.06052226,  0.91555191,  0.19788074, ...,  0.44414152,
         1.72897707, -0.57444212],
       [ 1.58478005,  0.91555191,  1.53290826, ...,  0.32180699,
        -0.57837667, -0.57444212],
       [ 0.9539045 ,  0.91555191, -1.32786498, ...,  0.51236683,
        -0.57837667,  1.74081944]])

In [94]:
model=Sequential()
model.add(Dense(data_edited.shape[1],activation='relu',input_dim=data_edited.shape[1]))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [95]:
data_edited.shape[1]

11

In [96]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [97]:
model.fit(x_train,y_train,batch_size=10,epochs=10,verbose=1)

Train on 9000 samples
Epoch 1/10
9000/9000 [==============================] - 4s 465us/sample - loss: 0.4571 - accuracy: 0.8050
Epoch 2/10
9000/9000 [==============================] - 3s 298us/sample - loss: 0.4073 - accuracy: 0.8262
Epoch 3/10
9000/9000 [==============================] - 3s 299us/sample - loss: 0.3686 - accuracy: 0.8512
Epoch 4/10
9000/9000 [==============================] - 3s 299us/sample - loss: 0.3508 - accuracy: 0.8596
Epoch 5/10
9000/9000 [==============================] - 3s 299us/sample - loss: 0.3449 - accuracy: 0.8603
Epoch 6/10
9000/9000 [==============================] - 3s 302us/sample - loss: 0.3418 - accuracy: 0.8619
Epoch 7/10
9000/9000 [==============================] - 3s 303us/sample - loss: 0.3390 - accuracy: 0.8619
Epoch 8/10
9000/9000 [==============================] - 3s 306us/sample - loss: 0.3376 - accuracy: 0.8602
Epoch 9/10
9000/9000 [==============================] - 3s 307us/sample - loss: 0.3362 - accuracy: 0.8623
Epoch 10/10
9000/9000 [=

In [98]:
y_pred=model.predict_classes(x_test)

In [99]:
y_pred

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [70]:
y_test=y_test.to_numpy()

In [71]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [73]:
model.evaluate(x_test,y_test)

1000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[19634.4505, 0.463]

In [74]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [75]:
confusion_matrix(y_test,y_pred)

array([[312, 484],
       [ 53, 151]], dtype=int64)

In [76]:
accuracy_score(y_test,y_pred)

0.463